require:
  - rubocop-rspec
  - rubocop-rake

inherit_from:
  - ./rubocop/config.yml

AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/angry_boat-rails.rb
